/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FavoriteRequest } from '../../models/favorite-request';
import { StringResultCustomModel } from '../../models/string-result-custom-model';

export interface ApiFavoritesPost$Json$Params {
      body?: FavoriteRequest
}

export function apiFavoritesPost$Json(http: HttpClient, rootUrl: string, params?: ApiFavoritesPost$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<StringResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiFavoritesPost$Json.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/*+json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<StringResultCustomModel>;
    })
  );
}

apiFavoritesPost$Json.PATH = '/api/Favorites';
