/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FavoriteProductResponse {
  img?: string | null;
  isActive?: boolean;
  priceOutput?: number;
  productId?: number;
  productName?: string | null;
}
