/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Customer } from '../models/customer';
import { Product } from '../models/product';
export interface Favorite {
  createOn?: string;
  customer?: Customer;
  customerId?: number;
  favoriteId?: number;
  product?: Product;
  productId?: number;
}
