/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ProductResponseSale {
  finalPrice?: number;
  img?: string | null;
  name?: string | null;
  priceOutput?: number;
  productId?: number;
  saleOff?: number;
}
