/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { apiAuthGoogleSignInPost } from '../fn/auth/api-auth-google-sign-in-post';
import { ApiAuthGoogleSignInPost$Params } from '../fn/auth/api-auth-google-sign-in-post';

@Injectable({ providedIn: 'root' })
export class AuthService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `apiAuthGoogleSignInPost()` */
  static readonly ApiAuthGoogleSignInPostPath = '/api/Auth/GoogleSignIn';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `apiAuthGoogleSignInPost()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthGoogleSignInPost$Response(params?: ApiAuthGoogleSignInPost$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    return apiAuthGoogleSignInPost(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `apiAuthGoogleSignInPost$Response()` instead.
   *
   * This method sends `application/*+json` and handles request body of type `application/*+json`.
   */
  apiAuthGoogleSignInPost(params?: ApiAuthGoogleSignInPost$Params, context?: HttpContext): Observable<void> {
    return this.apiAuthGoogleSignInPost$Response(params, context).pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
