/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProductResponseSaleListResultCustomModel } from '../../models/product-response-sale-list-result-custom-model';

export interface ApiProductGetSaleOffProductsGet$Json$Params {
}

export function apiProductGetSaleOffProductsGet$Json(http: HttpClient, rootUrl: string, params?: ApiProductGetSaleOffProductsGet$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<ProductResponseSaleListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiProductGetSaleOffProductsGet$Json.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'text/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProductResponseSaleListResultCustomModel>;
    })
  );
}

apiProductGetSaleOffProductsGet$Json.PATH = '/api/Product/GetSaleOffProducts';
