/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GetListProductSpResultListResultCustomModel } from '../../models/get-list-product-sp-result-list-result-custom-model';

export interface ApiProductGetTopSellingProductsTopSellingGet$Plain$Params {
  top?: number;
}

export function apiProductGetTopSellingProductsTopSellingGet$Plain(http: HttpClient, rootUrl: string, params?: ApiProductGetTopSellingProductsTopSellingGet$Plain$Params, context?: HttpContext): Observable<StrictHttpResponse<GetListProductSpResultListResultCustomModel>> {
  const rb = new RequestBuilder(rootUrl, apiProductGetTopSellingProductsTopSellingGet$Plain.PATH, 'get');
  if (params) {
    rb.query('top', params.top, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/plain', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GetListProductSpResultListResultCustomModel>;
    })
  );
}

apiProductGetTopSellingProductsTopSellingGet$Plain.PATH = '/api/Product/GetTopSellingProducts/top-selling';
